Am = 3;
Ac = 6;
fm = 10;
fc = 100;
u = Am/Ac;
t = 0:0.001:1;
message = Am * cos(2 * pi * fm * t);
subplot(2, 2, 1);
plot(t, message);
title("Message signal");
x = 0:0.001:1;
carrier = Ac * cos(2 * pi * fc * t);
subplot(2, 2, 2);
plot(x, carrier);
title("Carrier Signal");
y = 0:0.001:1;
subplot(2, 2, 3);
Am = Ac .* (1 + u * (cos(2 * pi * fm * t))) .* cos(2 * pi * fc * t);
plot(t, Am);
title("Modulated Signal");